//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MosFontTool.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MosFontTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Error... 的本地化字符串。
        /// </summary>
        internal static string Caption_error {
            get {
                return ResourceManager.GetString("Caption_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export complete 的本地化字符串。
        /// </summary>
        internal static string Caption_exportMsg {
            get {
                return ResourceManager.GetString("Caption_exportMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hine 的本地化字符串。
        /// </summary>
        internal static string Caption_info {
            get {
                return ResourceManager.GetString("Caption_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap colorPicker {
            get {
                object obj = ResourceManager.GetObject("colorPicker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap complete {
            get {
                object obj = ResourceManager.GetObject("complete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Please input background color. 的本地化字符串。
        /// </summary>
        internal static string Err_backcolor_required {
            get {
                return ResourceManager.GetString("Err_backcolor_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input chars. 的本地化字符串。
        /// </summary>
        internal static string Err_char_required {
            get {
                return ResourceManager.GetString("Err_char_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select font. 的本地化字符串。
        /// </summary>
        internal static string Err_font_required {
            get {
                return ResourceManager.GetString("Err_font_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input forecolor 的本地化字符串。
        /// </summary>
        internal static string Err_forecolor_required {
            get {
                return ResourceManager.GetString("Err_forecolor_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 color mode validation failure. 的本地化字符串。
        /// </summary>
        internal static string Err_invalidateColorMode {
            get {
                return ResourceManager.GetString("Err_invalidateColorMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 scan mode validation failure. 的本地化字符串。
        /// </summary>
        internal static string Err_invalidateScanMode {
            get {
                return ResourceManager.GetString("Err_invalidateScanMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select size. 的本地化字符串。
        /// </summary>
        internal static string Err_size_required {
            get {
                return ResourceManager.GetString("Err_size_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap fontViewr {
            get {
                object obj = ResourceManager.GetObject("fontViewr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon fontViewrIcon {
            get {
                object obj = ResourceManager.GetObject("fontViewrIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 MosFontTool
        ///
        ///  by mostone@hotmail.com 的本地化字符串。
        /// </summary>
        internal static string Inf_about {
            get {
                return ResourceManager.GetString("Inf_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input array name. 的本地化字符串。
        /// </summary>
        internal static string Inf_arrayName_required {
            get {
                return ResourceManager.GetString("Inf_arrayName_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bitmap file export completed. 的本地化字符串。
        /// </summary>
        internal static string Inf_bmpExpdortComplete {
            get {
                return ResourceManager.GetString("Inf_bmpExpdortComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select color mode. 的本地化字符串。
        /// </summary>
        internal static string Inf_colorMode_required {
            get {
                return ResourceManager.GetString("Inf_colorMode_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font array export complete.
        ///
        ///Do you want to open output file? 的本地化字符串。
        /// </summary>
        internal static string Inf_openFileConfirm {
            get {
                return ResourceManager.GetString("Inf_openFileConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select scan mode. 的本地化字符串。
        /// </summary>
        internal static string Inf_scanMode_required {
            get {
                return ResourceManager.GetString("Inf_scanMode_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MosFontTool
        ///  By mostone@hotmail.com
        ///
        ///ABCDEFGHIJKLMNOPQRSTUVWXYZ
        ///abcdefghijklmnopqrstuvwxyz
        ///0123456789
        ///~!@#$%^&amp;*()_+
        ///心静自然凉 的本地化字符串。
        /// </summary>
        internal static string inputChars {
            get {
                return ResourceManager.GetString("inputChars", resourceCulture);
            }
        }
    }
}
